services:
  mysql:
    image: mysql:latest
    container_name: productServiceDocker
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: ProductServiceDB

    ports:
      - "3306:3306"
    volumes:
      - ./mysqlProduct:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
